/**
 * This class is generated by jOOQ
 */
package generated2.tables.records


import generated2.tables.MeWeather

import java.lang.Integer
import java.lang.String
import java.sql.Timestamp

import javax.annotation.Generated

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record11
import org.jooq.Row11
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = Array(
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	),
	comments = "This class is generated by jOOQ"
)
class MeWeatherRecord extends UpdatableRecordImpl[MeWeatherRecord](MeWeather.ME_WEATHER) with Record11[String, Integer, String, Integer, Integer, Integer, String, Timestamp, Integer, Integer, String] {

	/**
	 * Setter for <code>tour.ME_WEATHER.ID</code>. info:天气 ID
	 */
	def setId(value : String) : Unit = {
		setValue(0, value)
	}

	/**
	 * Getter for <code>tour.ME_WEATHER.ID</code>. info:天气 ID
	 */
	def getId : String = {
		val r = getValue(0)
		if (r == null) null else r.asInstanceOf[String]
	}

	/**
	 * Setter for <code>tour.ME_WEATHER.REGION</code>. info:天气 地区编码
	 */
	def setRegion(value : Integer) : Unit = {
		setValue(1, value)
	}

	/**
	 * Getter for <code>tour.ME_WEATHER.REGION</code>. info:天气 地区编码
	 */
	def getRegion : Integer = {
		val r = getValue(1)
		if (r == null) null else r.asInstanceOf[Integer]
	}

	/**
	 * Setter for <code>tour.ME_WEATHER.WT</code>. info:天气 天气现象
	 */
	def setWt(value : String) : Unit = {
		setValue(2, value)
	}

	/**
	 * Getter for <code>tour.ME_WEATHER.WT</code>. info:天气 天气现象
	 */
	def getWt : String = {
		val r = getValue(2)
		if (r == null) null else r.asInstanceOf[String]
	}

	/**
	 * Setter for <code>tour.ME_WEATHER.FH</code>. info:天气 预报时次
	 */
	def setFh(value : Integer) : Unit = {
		setValue(3, value)
	}

	/**
	 * Getter for <code>tour.ME_WEATHER.FH</code>. info:天气 预报时次
	 */
	def getFh : Integer = {
		val r = getValue(3)
		if (r == null) null else r.asInstanceOf[Integer]
	}

	/**
	 * Setter for <code>tour.ME_WEATHER.T1</code>. info:天气 晚上温度
	 */
	def setT1(value : Integer) : Unit = {
		setValue(4, value)
	}

	/**
	 * Getter for <code>tour.ME_WEATHER.T1</code>. info:天气 晚上温度
	 */
	def getT1 : Integer = {
		val r = getValue(4)
		if (r == null) null else r.asInstanceOf[Integer]
	}

	/**
	 * Setter for <code>tour.ME_WEATHER.T2</code>. info:天气 白天温度
	 */
	def setT2(value : Integer) : Unit = {
		setValue(5, value)
	}

	/**
	 * Getter for <code>tour.ME_WEATHER.T2</code>. info:天气 白天温度
	 */
	def getT2 : Integer = {
		val r = getValue(5)
		if (r == null) null else r.asInstanceOf[Integer]
	}

	/**
	 * Setter for <code>tour.ME_WEATHER.WIND</code>. info:天气 风向
	 */
	def setWind(value : String) : Unit = {
		setValue(6, value)
	}

	/**
	 * Getter for <code>tour.ME_WEATHER.WIND</code>. info:天气 风向
	 */
	def getWind : String = {
		val r = getValue(6)
		if (r == null) null else r.asInstanceOf[String]
	}

	/**
	 * Setter for <code>tour.ME_WEATHER.TIME</code>. info:天气 时间
	 */
	def setTime(value : Timestamp) : Unit = {
		setValue(7, value)
	}

	/**
	 * Getter for <code>tour.ME_WEATHER.TIME</code>. info:天气 时间
	 */
	def getTime : Timestamp = {
		val r = getValue(7)
		if (r == null) null else r.asInstanceOf[Timestamp]
	}

	/**
	 * Setter for <code>tour.ME_WEATHER.W1</code>. info:天气 晚上天气现象代码
	 */
	def setW1(value : Integer) : Unit = {
		setValue(8, value)
	}

	/**
	 * Getter for <code>tour.ME_WEATHER.W1</code>. info:天气 晚上天气现象代码
	 */
	def getW1 : Integer = {
		val r = getValue(8)
		if (r == null) null else r.asInstanceOf[Integer]
	}

	/**
	 * Setter for <code>tour.ME_WEATHER.W2</code>. info:天气 白天天气现象代码
	 */
	def setW2(value : Integer) : Unit = {
		setValue(9, value)
	}

	/**
	 * Getter for <code>tour.ME_WEATHER.W2</code>. info:天气 白天天气现象代码
	 */
	def getW2 : Integer = {
		val r = getValue(9)
		if (r == null) null else r.asInstanceOf[Integer]
	}

	/**
	 * Setter for <code>tour.ME_WEATHER.RESOURCECODE</code>. info:天气 资源编码
	 */
	def setResourcecode(value : String) : Unit = {
		setValue(10, value)
	}

	/**
	 * Getter for <code>tour.ME_WEATHER.RESOURCECODE</code>. info:天气 资源编码
	 */
	def getResourcecode : String = {
		val r = getValue(10)
		if (r == null) null else r.asInstanceOf[String]
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------
	override def key() : Record1[String] = {
		return super.key.asInstanceOf[ Record1[String] ]
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	override def fieldsRow : Row11[String, Integer, String, Integer, Integer, Integer, String, Timestamp, Integer, Integer, String] = {
		super.fieldsRow.asInstanceOf[ Row11[String, Integer, String, Integer, Integer, Integer, String, Timestamp, Integer, Integer, String] ]
	}

	override def valuesRow : Row11[String, Integer, String, Integer, Integer, Integer, String, Timestamp, Integer, Integer, String] = {
		super.valuesRow.asInstanceOf[ Row11[String, Integer, String, Integer, Integer, Integer, String, Timestamp, Integer, Integer, String] ]
	}
	override def field1 : Field[String] = MeWeather.ME_WEATHER.ID
	override def field2 : Field[Integer] = MeWeather.ME_WEATHER.REGION
	override def field3 : Field[String] = MeWeather.ME_WEATHER.WT
	override def field4 : Field[Integer] = MeWeather.ME_WEATHER.FH
	override def field5 : Field[Integer] = MeWeather.ME_WEATHER.T1
	override def field6 : Field[Integer] = MeWeather.ME_WEATHER.T2
	override def field7 : Field[String] = MeWeather.ME_WEATHER.WIND
	override def field8 : Field[Timestamp] = MeWeather.ME_WEATHER.TIME
	override def field9 : Field[Integer] = MeWeather.ME_WEATHER.W1
	override def field10 : Field[Integer] = MeWeather.ME_WEATHER.W2
	override def field11 : Field[String] = MeWeather.ME_WEATHER.RESOURCECODE
	override def value1 : String = getId
	override def value2 : Integer = getRegion
	override def value3 : String = getWt
	override def value4 : Integer = getFh
	override def value5 : Integer = getT1
	override def value6 : Integer = getT2
	override def value7 : String = getWind
	override def value8 : Timestamp = getTime
	override def value9 : Integer = getW1
	override def value10 : Integer = getW2
	override def value11 : String = getResourcecode

	override def value1(value : String) : MeWeatherRecord = {
		setId(value)
		this
	}

	override def value2(value : Integer) : MeWeatherRecord = {
		setRegion(value)
		this
	}

	override def value3(value : String) : MeWeatherRecord = {
		setWt(value)
		this
	}

	override def value4(value : Integer) : MeWeatherRecord = {
		setFh(value)
		this
	}

	override def value5(value : Integer) : MeWeatherRecord = {
		setT1(value)
		this
	}

	override def value6(value : Integer) : MeWeatherRecord = {
		setT2(value)
		this
	}

	override def value7(value : String) : MeWeatherRecord = {
		setWind(value)
		this
	}

	override def value8(value : Timestamp) : MeWeatherRecord = {
		setTime(value)
		this
	}

	override def value9(value : Integer) : MeWeatherRecord = {
		setW1(value)
		this
	}

	override def value10(value : Integer) : MeWeatherRecord = {
		setW2(value)
		this
	}

	override def value11(value : String) : MeWeatherRecord = {
		setResourcecode(value)
		this
	}

	override def values(value1 : String, value2 : Integer, value3 : String, value4 : Integer, value5 : Integer, value6 : Integer, value7 : String, value8 : Timestamp, value9 : Integer, value10 : Integer, value11 : String) : MeWeatherRecord = {
		this.value1(value1)
		this.value2(value2)
		this.value3(value3)
		this.value4(value4)
		this.value5(value5)
		this.value6(value6)
		this.value7(value7)
		this.value8(value8)
		this.value9(value9)
		this.value10(value10)
		this.value11(value11)
		this
	}

	/**
	 * Create a detached, initialised MeWeatherRecord
	 */
	def this(id : String, region : Integer, wt : String, fh : Integer, t1 : Integer, t2 : Integer, wind : String, time : Timestamp, w1 : Integer, w2 : Integer, resourcecode : String) = {
		this()

		setValue(0, id)
		setValue(1, region)
		setValue(2, wt)
		setValue(3, fh)
		setValue(4, t1)
		setValue(5, t2)
		setValue(6, wind)
		setValue(7, time)
		setValue(8, w1)
		setValue(9, w2)
		setValue(10, resourcecode)
	}
}
