/**
 * This class is generated by jOOQ
 */
package generated2


import generated2.tables.MeEnviprotect
import generated2.tables.MeWeather
import generated2.tables.TourBus

import javax.annotation.Generated


/**
 * Convenience access to all tables in tour
 */
@Generated(
	value = Array(
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	),
	comments = "This class is generated by jOOQ"
)
object Tables {

	/**
	 * The table tour.ME_ENVIPROTECT
	 */
	val ME_ENVIPROTECT = generated2.tables.MeEnviprotect.ME_ENVIPROTECT

	/**
	 * The table tour.ME_WEATHER
	 */
	val ME_WEATHER = generated2.tables.MeWeather.ME_WEATHER

	/**
	 * The table tour.TOUR_BUS
	 */
	val TOUR_BUS = generated2.tables.TourBus.TOUR_BUS
}
